project_id = "wwkwoxxcprnjjufkbzac"

[functions.process_lease]
verify_jwt = false

[functions.retry_lease]
verify_jwt = false

[functions.send-lease-notifications]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false
