import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.leases': 'Leases',
    'nav.imports': 'Imports',
    'nav.reports': 'Reports',
    'nav.notifications': 'Notifications',
    'nav.integrations': 'Integrations',
    'nav.workspace': 'Workspace',
    'nav.account': 'Account',
    'nav.settings': 'Settings',
    'nav.documents': 'Documents',
    'nav.upgrade_for_more': 'Upgrade for more',
    'nav.account_settings': 'Account Settings',
    'nav.help_support': 'Help & Support',
    'nav.log_out': 'Log Out',
    
    // Landing Page - Nav
    'landing.nav.product': 'Product',
    'landing.nav.pricing': 'Pricing',
    'landing.nav.security': 'Security',
    'landing.nav.faq': 'FAQ',
    'landing.nav.sign_in': 'Sign in',
    'landing.nav.get_started': 'Get Started',
    
    // Landing Page - Hero
    'landing.hero.badge': 'Simple Lease Management for Growing Businesses',
    'landing.hero.headline': 'Know what you owe,',
    'landing.hero.headline_accent': "when it's due",
    'landing.hero.subheadline': 'LeaseIO extracts key terms from your leases in minutes. Track renewals, manage rent schedules, and never miss a deadline—no accounting complexity required.',
    'landing.hero.cta_trial': 'Start Free Trial',
    'landing.hero.cta_signin': 'Sign In',
    'landing.hero.trust_setup': '5-minute setup',
    'landing.hero.trust_ai': 'AI-powered extraction',
    'landing.hero.trust_security': 'Bank-grade security',
    'landing.hero.demo_coming': 'Interactive Demo Coming Soon',
    
    // Landing Page - Features
    'landing.features.title': 'Built for operators, not accountants',
    'landing.features.subtitle': 'No complex accounting standards. No journal entries. Just simple, clear visibility into your lease obligations.',
    'landing.features.ai_extraction.title': 'AI Lease Extraction',
    'landing.features.ai_extraction.desc': 'Upload a PDF and our AI extracts key terms, dates, parties, and rent schedules in minutes—not hours.',
    'landing.features.deadline_tracking.title': 'Deadline Tracking',
    'landing.features.deadline_tracking.desc': "Never miss a renewal window or expiration date. Visual calendar shows what's coming up across your portfolio.",
    'landing.features.rent_schedule.title': 'Rent Schedule Management',
    'landing.features.rent_schedule.desc': 'Track escalations, step increases, and rent changes. Know exactly what you owe each month.',
    'landing.features.notifications.title': 'Smart Notifications',
    'landing.features.notifications.desc': 'Get email alerts for renewals, expirations, and payment due dates. Customize timing to match your workflow.',
    'landing.features.rent_roll.title': 'One-Click Rent Roll',
    'landing.features.rent_roll.desc': 'Export your entire portfolio to CSV with one click. Total monthly rent, annual obligations, and more.',
    'landing.features.security.title': 'Secure & Private',
    'landing.features.security.desc': 'Bank-grade encryption keeps your lease documents safe. Your data is never shared or used for training.',
    
    // Landing Page - Footer
    'landing.footer.description': 'AI-powered lease abstraction and operations for modern businesses.',
    'landing.footer.support': 'Support',
    
    // Landing Page - FAQ
    'landing.faq.document_count.q': 'What counts as a document?',
    'landing.faq.document_count.a': 'Each master lease counts as one document. Each amendment to a lease also counts as one document. So a master lease with two amendments would use 3 of your document limit.',
    'landing.faq.ai_extraction.q': 'How does the AI extraction work?',
    'landing.faq.ai_extraction.a': 'Our AI reads your PDF lease document and extracts key information like parties, dates, rent amounts, escalation schedules, and important clauses. You then review and confirm the extracted data before finalizing.',
    'landing.faq.edit_data.q': 'Can I edit the extracted data?',
    'landing.faq.edit_data.a': 'Absolutely. After AI extraction, you review everything in a side-by-side view with the original PDF. You can edit any field before finalizing the lease abstract.',
    'landing.faq.document_limit.q': 'What happens if I hit my document limit?',
    'landing.faq.document_limit.a': "You won't be able to upload new documents until you upgrade your plan or your billing period resets. Existing documents remain fully accessible.",
    'landing.faq.quickbooks.q': 'How does QuickBooks integration work?',
    'landing.faq.quickbooks.a': "Available on the Business plan, you connect your QuickBooks Online account via OAuth. Choose whether you're a lessor (creates invoices) or lessee (creates bills), match vendors/customers, and we'll automatically create transactions based on your rent schedule.",
    'landing.faq.data_ownership.q': 'Who owns my data?',
    'landing.faq.data_ownership.a': 'You do. Your documents and extracted data belong to you. You can export everything at any time, and if you close your account, we delete your data within 30 days.',
    'landing.faq.security.q': 'Is my data secure?',
    'landing.faq.security.a': 'Yes. We use AES-256 encryption for data at rest and TLS 1.3 for data in transit. Our infrastructure is SOC 2 compliant, and we support role-based access controls within your workspace.',
    'landing.faq.multiple_users.q': 'Can I have multiple users in my workspace?',
    'landing.faq.multiple_users.a': 'Yes. You can invite team members with different roles: Owner, Admin, Manager, Reviewer, or Read-only. Each role has specific permissions for billing, integrations, and lease management.',
    
    // Plan Feature Translations
    'plan.feature.1_lease': '1 lease document',
    'plan.feature.5_leases': '5 lease documents',
    'plan.feature.15_leases': '15 lease documents',
    'plan.feature.50_leases': '50 lease documents',
    
    // Landing Page - How It Works
    'landing.how.title': 'How it works',
    'landing.how.subtitle': 'Get from PDF to actionable insights in four simple steps.',
    'landing.how.step1.title': 'Upload',
    'landing.how.step1.desc': 'Drop your lease PDF into LeaseIO. Master leases and amendments supported.',
    'landing.how.step2.title': 'Extract',
    'landing.how.step2.desc': 'Our AI reads the document and extracts key terms, dates, rent schedules, and more.',
    'landing.how.step3.title': 'Review',
    'landing.how.step3.desc': 'Review extracted data side-by-side with the original PDF. Make corrections if needed.',
    'landing.how.step4.title': 'Automate',
    'landing.how.step4.desc': 'Finalize and unlock notifications, escalation tracking, and accounting sync.',
    
    // Landing Page - Pricing
    'landing.pricing.title': 'Simple pricing, no surprises',
    'landing.pricing.subtitle': 'Start with a 14-day free trial. No credit card required. Upgrade as your portfolio grows.',
    'landing.pricing.monthly': 'Monthly',
    'landing.pricing.annual': 'Annual',
    'landing.pricing.save': 'Save',
    'landing.pricing.free': 'Free',
    'landing.pricing.most_popular': 'Most Popular',
    'landing.pricing.per_month': '/mo',
    'landing.pricing.per_year': '/year',
    'landing.pricing.get_started': 'Get Started',
    'landing.pricing.start_trial': 'Start Free Trial',
    'landing.pricing.lease': 'lease',
    'landing.pricing.leases': 'leases',
    'landing.pricing.custom': 'Need more?',
    'landing.pricing.contact': 'Contact us',
    'landing.pricing.enterprise': 'for custom enterprise pricing.',
    
    // Landing Page - Security
    'landing.security.title': 'Enterprise-grade security',
    'landing.security.subtitle': 'Your lease documents contain sensitive business information. We treat security as a first-class concern, not an afterthought.',
    'landing.security.encryption.title': 'End-to-end encryption',
    'landing.security.encryption.desc': 'Your documents are encrypted at rest and in transit using AES-256.',
    'landing.security.access.title': 'Role-based access',
    'landing.security.access.desc': 'Control who can view, edit, or manage leases with granular permissions.',
    'landing.security.audit.title': 'Audit logging',
    'landing.security.audit.desc': 'Every action is logged for compliance and accountability.',
    'landing.security.hosting.title': 'SOC 2 compliant hosting',
    'landing.security.hosting.desc': 'Hosted on enterprise-grade infrastructure with 99.9% uptime.',
    
    // Landing Page - FAQ
    'landing.faq.title': 'Frequently asked questions',
    'landing.faq.subtitle': 'Everything you need to know about LeaseIO.',
    
    // Landing Page - Footer
    'landing.footer.product': 'Product',
    'landing.footer.company': 'Company',
    'landing.footer.legal': 'Legal',
    'landing.footer.features': 'Features',
    'landing.footer.pricing': 'Pricing',
    'landing.footer.security': 'Security',
    'landing.footer.about': 'About',
    'landing.footer.blog': 'Blog',
    'landing.footer.careers': 'Careers',
    'landing.footer.contact': 'Contact',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.terms': 'Terms of Service',
    'landing.footer.copyright': '© 2024 LeaseIO. All rights reserved.',
    
    // Dashboard
    'dashboard.welcome_back': 'Welcome back',
    'dashboard.upload_lease': 'Upload Lease',
    'dashboard.active_leases': 'Active Leases',
    'dashboard.action_required': 'Action Required',
    'dashboard.expiring_90_days': 'Expiring in 90 Days',
    'dashboard.finalized': 'Finalized',
    'dashboard.total_monthly_rent': 'Total Monthly Rent',
    'dashboard.annual_obligation': 'Annual Obligation',
    'dashboard.next_payment_due': 'Next Payment Due',
    'dashboard.rent_per_lease': 'Rent Per Lease',
    'dashboard.active_lease': 'active lease',
    'dashboard.active_leases_count': 'active leases',
    'dashboard.total_for_year': 'Total for the year',
    'dashboard.no_upcoming_payments': 'No upcoming payments',
    'dashboard.average_monthly': 'Average monthly',
    'dashboard.days': 'days',
    'dashboard.upcoming_events': 'Upcoming Events',
    'dashboard.view_all': 'View all',
    'dashboard.no_upcoming_events': 'No upcoming events',
    'dashboard.events_appear_here': 'Events will appear here as your leases approach key dates',
    'dashboard.today': 'Today',
    'dashboard.tomorrow': 'Tomorrow',
    'dashboard.renewal': 'Renewal',
    'dashboard.escalation': 'Escalation',
    'dashboard.expiration': 'Expiration',
    'dashboard.payment': 'Payment',
    'dashboard.lease_expires': 'Lease expires',
    'dashboard.renewal_window_opens': 'Renewal window opens',
    'dashboard.rent_payment_due': 'Rent payment due',
    'dashboard.properties': 'properties',
    
    // Lease Review
    'lease.review': 'Review Lease',
    'lease.parties': 'Parties',
    'lease.landlord': 'Landlord',
    'lease.tenant': 'Tenant',
    'lease.property_term': 'Property & Term',
    'lease.property_address': 'Property Address',
    'lease.commencement_date': 'Commencement Date',
    'lease.expiration_date': 'Expiration Date',
    'lease.rent_schedule': 'Rent Schedule',
    'lease.financial_terms': 'Additional Financial Terms',
    'lease.base_rent': 'Base Rent (Legacy)',
    'lease.rent_frequency': 'Rent Frequency',
    'lease.security_deposit': 'Security Deposit',
    'lease.escalation_clauses': 'Escalation Clauses (Description)',
    'lease.additional_terms': 'Additional Terms',
    'lease.renewal_options': 'Renewal Options',
    'lease.termination_clauses': 'Termination Clauses',
    'lease.key_dates': 'Key Dates & Notifications',
    'lease.document': 'Document',
    'lease.download_original': 'Download Original',
    'lease.identified_risks': 'Identified Risks',
    'lease.no_risks': 'No risks identified',
    'lease.status': 'Status',
    'lease.approve': 'Approve Lease',
    'lease.approved': 'Approved',
    'lease.active': 'Active',
    'lease.confirm': 'Confirm',
    'lease.edit': 'Edit',
    'lease.save': 'Save',
    'lease.back': 'Back',
    'lease.finalize': 'Finalize',
    'lease.review_required': 'Review Required',
    'lease.review_edit_info': 'Review and edit the extracted information below, then save your changes before finalizing.',
    'lease.finalized': 'Finalized',
    'lease.finalized_info': 'This lease has been reviewed and finalized.',
    'lease.approved_info': 'This lease has been approved and is now active.',
    'lease.processing': 'Processing',
    'lease.uploaded': 'Uploaded',
    'lease.ready': 'Ready',
    'lease.failed': 'Failed',
    'lease.ai_risks_desc': 'AI-identified potential issues in this lease',
    'lease.not_found': 'Lease not found',
    'lease.back_to_leases': 'Back to Leases',
    'lease.draft': 'Draft',
    'lease.needs_review': 'Needs Review',
    'lease.archived': 'Archived',
    'lease.amendment': 'Amendment',
    'lease.address_pending': 'Address pending',
    
    // Rent Schedule
    'rent_schedule.title': 'Rent Schedule',
    'rent_schedule.description': 'Complete rent history extracted from the lease document',
    'rent_schedule.current_monthly': 'Current Monthly Rent',
    'rent_schedule.escalation_type': 'Escalation Type',
    'rent_schedule.next_increase': 'Next Increase',
    'rent_schedule.not_specified': 'Not specified',
    'rent_schedule.period': 'Period',
    'rent_schedule.monthly': 'Monthly',
    'rent_schedule.annual': 'Annual',
    'rent_schedule.notes': 'Notes',
    'rent_schedule.current': 'Current',
    'rent_schedule.ongoing': 'Ongoing',
    'rent_schedule.no_schedule': 'No rent schedule extracted',
    'rent_schedule.check_base_rent': 'Rent information may be in the base rent fields',
    
    // Leases Page
    'leases.title': 'Leases',
    'leases.portfolio': 'Your lease portfolio',
    'leases.search': 'Search leases...',
    'leases.filter_expiration': 'Filter by expiration',
    'leases.all_leases': 'All leases',
    'leases.expiring_30': 'Expiring in 30 days',
    'leases.expiring_90': 'Expiring in 90 days',
    'leases.expiring_year': 'Expiring this year',
    'leases.property': 'Property',
    'leases.tenant': 'Tenant',
    'leases.landlord': 'Landlord',
    'leases.dates': 'Dates',
    'leases.rent': 'Rent',
    'leases.sqft': 'Sq. Ft.',
    'leases.start': 'Start',
    'leases.end': 'End',
    'leases.actions': 'Actions',
    'leases.no_leases': 'No leases yet',
    'leases.upload_first': 'Upload your first lease to get started',
    'leases.no_match': 'No leases match your filters',
    'leases.view_details': 'View details',
    'leases.delete': 'Delete',
    'leases.expired': 'Expired',
    'leases.active_leases': 'active leases',
    
    // Import History
    'import.history': 'Import History',
    'import.documents_imported': 'documents imported',
    'import.upload_lease': 'Upload Lease',
    'import.no_imports': 'No imports yet',
    'import.upload_first': 'Upload your first lease document to get started',
    'import.search_filename': 'Search by filename...',
    'import.filename': 'Filename',
    'import.uploaded': 'Uploaded',
    'import.processed': 'Processed',
    'import.actions': 'Actions',
    'import.retry': 'Retry',
    'import.view': 'View lease',
    'import.delete': 'Delete',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Stay on top of important dates',
    'notifications.no_notifications': 'No notifications',
    'notifications.all_caught_up': "You're all caught up!",
    'notifications.view_all': 'View all notifications',
    'notifications.tab_all': 'All Confirmed',
    'notifications.tab_upcoming': 'Upcoming Alerts',
    'notifications.tab_sent': 'Already Sent',
    'notifications.view_leases': 'View Leases',
    'notifications.view_lease': 'View Lease',
    'notifications.disable': 'Disable Notifications',
    'notifications.type.renewal_window': 'Renewal Window',
    'notifications.type.escalation': 'Rent Escalation',
    'notifications.type.expiration': 'Lease Expiration',
    'notifications.type.commencement': 'Lease Commencement',
    'notifications.type.custom': 'Custom',
    'notifications.sent': 'Sent',
    'notifications.scheduled': 'Scheduled',
    'notifications.past': 'Past',
    'notifications.email_off': 'Email Off',
    'notifications.alerts': 'Alerts',
    'notifications.days_before': 'days before',
    'notifications.unknown_property': 'Unknown Property',
    'notifications.hours_ago': 'hours ago',
    'notifications.day_ago': 'day ago',
    'notifications.custom': 'Custom',
    
    // Notification Detail
    'notifications.detail_title': 'Notification Details',
    'notifications.not_found': 'Notification not found',
    'notifications.back_to_list': 'Back to Notifications',
    'notifications.error_loading': 'Failed to load notification',
    'notifications.error_updating': 'Failed to update notification',
    'notifications.email_disabled': 'Email notifications disabled',
    'notifications.email_enabled': 'Email notifications enabled',
    'notifications.confirmed': 'Confirmed',
    'notifications.days_ago': '{{count}} days ago',
    'notifications.days_remaining': '{{count}} days remaining',
    'notifications.event_passed': 'Event has passed',
    'notifications.time_remaining': 'Time remaining',
    'notifications.associated_lease': 'Associated Lease',
    'notifications.email_settings': 'Email Notifications',
    'notifications.email_on': 'Email alerts enabled',
    'notifications.alert_schedule': 'Alert schedule',
    'notifications.enable': 'Enable',
    'notifications.last_sent': 'Last notification sent',
    
    // Notification Configurator
    'notifications.config.title': 'Key Dates & Notifications',
    'notifications.config.description': 'Confirm dates and enable notifications for important events',
    'notifications.config.confirmed_count': 'confirmed',
    'notifications.config.active_alerts': 'active alerts',
    'notifications.config.no_dates': 'No key dates found. Add dates above to set up notifications.',
    'notifications.config.unconfirmed': 'Unconfirmed',
    'notifications.config.notify_me': 'Notify me:',
    'notifications.config.email_enabled': 'Email enabled',
    'notifications.config.off': 'Off',
    'notifications.config.unconfirm': 'Unconfirm',
    'notifications.config.add_custom': 'Add Custom Date',
    'notifications.config.date': 'Date',
    'notifications.config.description_label': 'Description',
    'notifications.config.description_placeholder': 'e.g., Insurance renewal deadline',
    'notifications.config.add_date': 'Add Date',
    'notifications.config.save': 'Save Notification Preferences',
    'notifications.config.days_before': 'days before',
    'notifications.config.lease_commencement': 'Lease Commencement',
    'notifications.config.lease_expiration': 'Lease Expiration',
    'notifications.config.renewal_window': 'Renewal Window',
    'notifications.config.rent_escalation': 'Rent Escalation',
    'notifications.config.custom_date': 'Custom Date',
    'notifications.config.commencement_desc': 'Lease commencement date',
    'notifications.config.expiration_desc': 'Lease expiration date',
    'notifications.config.renewal_desc': 'Renewal decision window opens',
    'notifications.config.escalation_desc': 'Rent escalation to',
    'notifications.config.per_month': '/month',
    
    // Account Settings
    'account.title': 'Account Settings',
    'account.subtitle': 'Manage your personal account',
    'account.profile': 'Profile',
    'account.security': 'Security',
    'account.notifications': 'Notifications',
    'account.data_privacy': 'Data & Privacy',
    'account.subscription': 'Subscription',
    'account.personal_info': 'Personal Information',
    'account.update_details': 'Update your personal details',
    'account.first_name': 'First Name',
    'account.last_name': 'Last Name',
    'account.email': 'Email',
    'account.phone': 'Phone (for SMS notifications)',
    'account.company': 'Company Name',
    'account.timezone': 'Timezone',
    'account.save_changes': 'Save Changes',
    'account.saving': 'Saving...',
    'account.change_password': 'Change Password',
    'account.update_password': 'Update your account password',
    'account.current_password': 'Current Password',
    'account.new_password': 'New Password',
    'account.confirm_password': 'Confirm New Password',
    'account.update_password_btn': 'Update Password',
    'account.updating': 'Updating...',
    'account.security_activity': 'Recent Security Activity',
    'account.review_logins': 'Review recent logins and security events',
    'account.current_session': 'Current session',
    'account.password_changed': 'Password changed',
    'account.logout_other': 'Log out of other sessions',
    'account.notification_prefs': 'Notification Preferences',
    'account.choose_alerts': 'Choose how you want to receive alerts',
    'account.email_notifications': 'Email Notifications',
    'account.email_notifications_desc': 'Receive lease alerts via email',
    'account.sms_notifications': 'SMS Notifications',
    'account.sms_notifications_desc': 'Receive critical alerts via SMS',
    'account.quiet_hours': 'Quiet Hours',
    'account.quiet_hours_desc': "Don't send notifications between 10 PM - 7 AM",
    'account.export_data': 'Export Your Data',
    'account.export_data_desc': 'Download a copy of all your data in this workspace',
    'account.export_archive': 'This will create a downloadable archive containing all your leases, extracted data, and account information.',
    'account.export_btn': 'Export Data',
    'account.exporting': 'Exporting...',
    'account.delete_account': 'Delete Account',
    'account.delete_account_desc': 'Permanently delete your account and all associated data',
    'account.delete_warning': 'This action cannot be undone. All your data, including leases, extracted information, and workspace settings will be permanently deleted.',
    'account.delete_confirm': 'Are you absolutely sure?',
    'account.delete_confirm_desc': 'This action cannot be undone. This will permanently delete your account and remove all your data from our servers.',
    'account.current_plan': 'Current Plan',
    'account.renews_on': 'Your subscription renews on',
    'account.document_usage': 'Document Usage',
    'account.manage_payment': 'Manage Payment Method',
    'account.billing_contact': 'Billing Contact',
    'account.invoices_sent': 'Invoices are sent to this email',
    'account.update_billing': 'Update Billing Contact',
    'account.available_plans': 'Available Plans',
    'account.invoice_history': 'Invoice History',
    'account.download_invoices': 'Download past invoices for your records',
    'account.cancel_subscription': 'Cancel Subscription',
    'account.cancel_subscription_desc': 'Cancel your subscription at the end of the current billing period',
    'account.cancel_warning': 'Your subscription will remain active until the end of your current billing period. You can reactivate anytime before then.',
    'account.cancel_confirm': 'Cancel your subscription?',
    'account.cancel_confirm_desc': "Your subscription will remain active until the end of your current billing period. After that, you'll lose access to premium features.",
    'account.keep_subscription': 'Keep Subscription',
    'account.free': 'Free',
    'account.current': 'Current',
    'account.downgrade': 'Downgrade',
    'account.free_tier': 'Free Tier',
    'account.leases': 'leases',
    'account.lease': 'lease',
    'account.paid': 'Paid',
    
    // Workspace Settings
    'workspace.title': 'Workspace Settings',
    'workspace.subtitle': 'Manage your workspace configuration',
    'workspace.general': 'General',
    'workspace.members': 'Members',
    'workspace.notifications': 'Notifications',
    'workspace.security': 'Security',
    'workspace.details': 'Workspace Details',
    'workspace.basic_info': 'Basic information about your workspace',
    'workspace.name': 'Workspace Name',
    'workspace.default_timezone': 'Default Timezone',
    'workspace.timezone_desc': 'Used for scheduling notifications and displaying dates',
    'workspace.save_changes': 'Save Changes',
    'workspace.saving': 'Saving...',
    'workspace.team_members': 'Team Members',
    'workspace.manage_access': 'Manage who has access to this workspace',
    'workspace.invite_member': 'Invite Member',
    'workspace.no_members': 'No team members yet',
    'workspace.only_one': "You're the only one with access to this workspace",
    'workspace.owner': 'Owner',
    'workspace.admin': 'Admin',
    'workspace.editor': 'Editor',
    'workspace.viewer': 'Viewer',
    'workspace.notification_settings': 'Default Notification Settings',
    'workspace.notification_timing': 'Configure default timing for lease notifications',
    'workspace.reminder_days': 'Default Reminder (days before)',
    'workspace.reminder_desc': 'How many days before an event to send the first notification',
    'workspace.audit_log': 'Audit Log',
    'workspace.view_activity': 'View recent activity in your workspace',
    'workspace.logs_appear': 'Audit logs will appear here',
    
    // Integrations
    'integrations.title': 'Integrations',
    'integrations.subtitle': 'Connect LeaseIO with your other tools',
    'integrations.quickbooks': 'QuickBooks Online',
    'integrations.quickbooks_desc': 'Sync lease payments and receivables with your accounting system. Automate invoice creation and bill tracking.',
    'integrations.email': 'Email Notifications',
    'integrations.email_desc': 'Send automated email alerts for renewals, escalations, and expirations.',
    'integrations.sms': 'SMS Notifications',
    'integrations.sms_desc': 'Receive critical lease alerts via SMS for time-sensitive events.',
    'integrations.connected': 'Connected',
    'integrations.configure': 'Configure',
    'integrations.disconnect': 'Disconnect',
    'integrations.connect': 'Connect',
    'integrations.upgrade_business': 'Upgrade to Business',
    'integrations.guide': 'Integration Guide',
    'integrations.guide_desc': 'Learn how to get the most out of your integrations',
    'integrations.step1': '1. Connect Your Account',
    'integrations.step1_desc': 'Use OAuth to securely connect your external accounts without sharing passwords.',
    'integrations.step2': '2. Configure Settings',
    'integrations.step2_desc': 'Choose how data should flow between LeaseIO and your connected services.',
    'integrations.step3': '3. Monitor Activity',
    'integrations.step3_desc': 'Review sync logs and troubleshoot any issues from the integration dashboard.',
    
    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Portfolio analytics and insights',
    'reports.export_all': 'Export All',
    'reports.rent_roll': 'Rent Roll Export',
    'reports.rent_roll_desc': 'Download a complete rent roll of your portfolio as a CSV file',
    'reports.rent_roll_details': 'Includes property details, tenant information, rent amounts, lease dates, and a portfolio summary. Compatible with Excel and Google Sheets.',
    'reports.download_rent_roll': 'Download Rent Roll',
    'reports.generating': 'Generating...',
    'reports.portfolio_overview': 'Portfolio Overview',
    'reports.portfolio_overview_desc': 'High-level summary of all active leases, total committed rent, and key metrics.',
    'reports.renewal_pipeline': 'Renewal Pipeline',
    'reports.renewal_pipeline_desc': 'Track upcoming renewals with projected impact and action recommendations.',
    'reports.escalation_calendar': 'Escalation Calendar',
    'reports.escalation_calendar_desc': 'View all scheduled rent escalations with projected increases.',
    'reports.rent_projections': 'Rent Projections',
    'reports.rent_projections_desc': 'Forecast future rent obligations based on current lease terms and escalations.',
    'reports.view_report': 'View Report',
    'reports.monthly_overview': 'Monthly Rent Overview',
    'reports.monthly_overview_desc': 'Total committed rent across all active leases',
    'reports.charts_appear': 'Charts will appear once you have finalized leases',
    'reports.unlock_advanced': 'Unlock Advanced Reports',
    'reports.unlock_desc': 'Upgrade to the Business plan to access portfolio analytics, renewal pipelines, escalation calendars, and rent projections.',
    
    // Empty States
    'empty.no_leases': 'No leases yet',
    'empty.upload_first': 'Upload your first lease document to get started. Our AI will automatically extract key terms, dates, and financial information for you.',
    'empty.upload_first_lease': 'Upload Your First Lease',
    'empty.supports_pdf': 'Supports PDF files up to 50MB',
    
    // Common
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.upload': 'Upload',
    'common.processing': 'Processing',
    'common.loading': 'Loading...',
    'common.page': 'Page',
    'common.search': 'Search',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upgrade': 'Upgrade',
    'common.business_plan': 'Business Plan',
    'common.search_placeholder': 'Search leases, parties, properties...',
    
    // Plan labels
    'plan.free': 'Free',
    'plan.starter': 'Starter',
    'plan.pro': 'Pro',
    'plan.business': 'Business',
    'plan.plan': 'Plan',
    'plan.upgrade': 'Upgrade',
    
    // Plan Features
    'plan.feature.lease_documents': 'lease documents',
    'plan.feature.ai_extraction': 'AI lease extraction',
    'plan.feature.basic_tracking': 'Basic rent tracking',
    'plan.feature.email_notifications': 'Email notifications',
    'plan.feature.rent_schedule': 'Rent schedule tracking',
    'plan.feature.rent_roll': 'Rent roll export',
    'plan.feature.document_storage': 'Document storage',
    'plan.feature.sms': 'SMS notifications',
    'plan.feature.risk_analysis': 'Risk analysis',
    'plan.feature.advanced_reports': 'Advanced reporting',
    'plan.feature.priority_support': 'Priority support',
    'plan.feature.team_access': 'Team access (5 seats)',
    'plan.feature.role_permissions': 'Role-based permissions',
    'plan.feature.quickbooks': 'QuickBooks integration',
    'plan.feature.custom_branding': 'Custom branding',
    'plan.feature.everything_starter': 'Everything in Starter',
    'plan.feature.everything_pro': 'Everything in Pro',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.leases': 'Arrendamientos',
    'nav.imports': 'Importaciones',
    'nav.reports': 'Informes',
    'nav.notifications': 'Notificaciones',
    'nav.integrations': 'Integraciones',
    'nav.workspace': 'Espacio de Trabajo',
    'nav.account': 'Cuenta',
    'nav.settings': 'Configuración',
    'nav.documents': 'Documentos',
    'nav.upgrade_for_more': 'Actualizar para más',
    'nav.account_settings': 'Configuración de Cuenta',
    'nav.help_support': 'Ayuda y Soporte',
    'nav.log_out': 'Cerrar Sesión',
    
    // Landing Page - Nav
    'landing.nav.product': 'Producto',
    'landing.nav.pricing': 'Precios',
    'landing.nav.security': 'Seguridad',
    'landing.nav.faq': 'FAQ',
    'landing.nav.sign_in': 'Iniciar Sesión',
    'landing.nav.get_started': 'Comenzar',
    
    // Landing Page - Hero
    'landing.hero.badge': 'Gestión Simple de Arrendamientos para Negocios en Crecimiento',
    'landing.hero.headline': 'Sepa lo que debe,',
    'landing.hero.headline_accent': 'cuándo vence',
    'landing.hero.subheadline': 'LeaseIO extrae términos clave de sus arrendamientos en minutos. Rastree renovaciones, administre calendarios de renta y nunca pierda una fecha límite—sin complejidad contable.',
    'landing.hero.cta_trial': 'Prueba Gratis',
    'landing.hero.cta_signin': 'Iniciar Sesión',
    'landing.hero.trust_setup': 'Configuración en 5 minutos',
    'landing.hero.trust_ai': 'Extracción con IA',
    'landing.hero.trust_security': 'Seguridad bancaria',
    'landing.hero.demo_coming': 'Demo Interactivo Próximamente',
    
    // Landing Page - Features
    'landing.features.title': 'Todo lo que necesita para gestionar arrendamientos',
    'landing.features.subtitle': 'Desde la extracción hasta las notificaciones, LeaseIO maneja la complejidad para que usted pueda enfocarse en su negocio.',
    
    // Landing Page - How It Works
    'landing.how.title': 'Cómo funciona',
    'landing.how.subtitle': 'Pase de PDF a información accionable en cuatro simples pasos.',
    'landing.how.step1.title': 'Subir',
    'landing.how.step1.desc': 'Suba su PDF de arrendamiento a LeaseIO. Soporta arrendamientos maestros y enmiendas.',
    'landing.how.step2.title': 'Extraer',
    'landing.how.step2.desc': 'Nuestra IA lee el documento y extrae términos clave, fechas, calendarios de renta y más.',
    'landing.how.step3.title': 'Revisar',
    'landing.how.step3.desc': 'Revise los datos extraídos junto al PDF original. Haga correcciones si es necesario.',
    'landing.how.step4.title': 'Automatizar',
    'landing.how.step4.desc': 'Finalice y active notificaciones, seguimiento de escalaciones y sincronización contable.',
    
    // Landing Page - Pricing
    'landing.pricing.title': 'Precios simples, sin sorpresas',
    'landing.pricing.subtitle': 'Comience con una prueba gratis de 14 días. No requiere tarjeta de crédito. Actualice a medida que crece su portafolio.',
    'landing.pricing.monthly': 'Mensual',
    'landing.pricing.annual': 'Anual',
    'landing.pricing.save': 'Ahorre',
    'landing.pricing.free': 'Gratis',
    'landing.pricing.most_popular': 'Más Popular',
    'landing.pricing.per_month': '/mes',
    'landing.pricing.per_year': '/año',
    'landing.pricing.get_started': 'Comenzar',
    'landing.pricing.start_trial': 'Prueba Gratis',
    'landing.pricing.lease': 'arrendamiento',
    'landing.pricing.leases': 'arrendamientos',
    'landing.pricing.custom': '¿Necesita más?',
    'landing.pricing.contact': 'Contáctenos',
    'landing.pricing.enterprise': 'para precios empresariales personalizados.',
    
    // Landing Page - Security
    'landing.security.title': 'Seguridad de nivel empresarial',
    'landing.security.subtitle': 'Sus documentos de arrendamiento contienen información comercial sensible. Tratamos la seguridad como una prioridad, no como algo secundario.',
    'landing.security.encryption.title': 'Cifrado de extremo a extremo',
    'landing.security.encryption.desc': 'Sus documentos están cifrados en reposo y en tránsito usando AES-256.',
    'landing.security.access.title': 'Acceso basado en roles',
    'landing.security.access.desc': 'Controle quién puede ver, editar o administrar arrendamientos con permisos granulares.',
    'landing.security.audit.title': 'Registro de auditoría',
    'landing.security.audit.desc': 'Cada acción se registra para cumplimiento y responsabilidad.',
    'landing.security.hosting.title': 'Alojamiento SOC 2',
    'landing.security.hosting.desc': 'Alojado en infraestructura empresarial con 99.9% de disponibilidad.',
    
    // Landing Page - FAQ
    'landing.faq.title': 'Preguntas frecuentes',
    'landing.faq.subtitle': 'Todo lo que necesita saber sobre LeaseIO.',
    
    // Landing Page - Footer
    'landing.footer.product': 'Producto',
    'landing.footer.company': 'Empresa',
    'landing.footer.legal': 'Legal',
    'landing.footer.features': 'Características',
    'landing.footer.pricing': 'Precios',
    'landing.footer.security': 'Seguridad',
    'landing.footer.about': 'Acerca de',
    'landing.footer.blog': 'Blog',
    'landing.footer.careers': 'Empleos',
    'landing.footer.contact': 'Contacto',
    'landing.footer.privacy': 'Política de Privacidad',
    'landing.footer.terms': 'Términos de Servicio',
    'landing.footer.copyright': '© 2024 LeaseIO. Todos los derechos reservados.',
    
    // Dashboard
    'dashboard.welcome_back': 'Bienvenido de nuevo',
    'dashboard.upload_lease': 'Subir Arrendamiento',
    'dashboard.active_leases': 'Arrendamientos Activos',
    'dashboard.action_required': 'Acción Requerida',
    'dashboard.expiring_90_days': 'Vencen en 90 Días',
    'dashboard.finalized': 'Finalizados',
    'dashboard.total_monthly_rent': 'Renta Mensual Total',
    'dashboard.annual_obligation': 'Obligación Anual',
    'dashboard.next_payment_due': 'Próximo Pago',
    'dashboard.rent_per_lease': 'Renta por Arrendamiento',
    'dashboard.active_lease': 'arrendamiento activo',
    'dashboard.active_leases_count': 'arrendamientos activos',
    'dashboard.total_for_year': 'Total del año',
    'dashboard.no_upcoming_payments': 'Sin pagos pendientes',
    'dashboard.average_monthly': 'Promedio mensual',
    'dashboard.days': 'días',
    'dashboard.upcoming_events': 'Próximos Eventos',
    'dashboard.view_all': 'Ver todos',
    'dashboard.no_upcoming_events': 'Sin eventos próximos',
    'dashboard.events_appear_here': 'Los eventos aparecerán aquí cuando sus arrendamientos se acerquen a fechas clave',
    'dashboard.today': 'Hoy',
    'dashboard.tomorrow': 'Mañana',
    'dashboard.renewal': 'Renovación',
    'dashboard.escalation': 'Escalación',
    'dashboard.expiration': 'Vencimiento',
    'dashboard.payment': 'Pago',
    'dashboard.lease_expires': 'Arrendamiento vence',
    'dashboard.renewal_window_opens': 'Ventana de renovación abre',
    'dashboard.rent_payment_due': 'Pago de renta pendiente',
    'dashboard.properties': 'propiedades',
    
    // Lease Review
    'lease.review': 'Revisar Arrendamiento',
    'lease.parties': 'Partes',
    'lease.landlord': 'Arrendador',
    'lease.tenant': 'Arrendatario',
    'lease.property_term': 'Propiedad y Plazo',
    'lease.property_address': 'Dirección de la Propiedad',
    'lease.commencement_date': 'Fecha de Inicio',
    'lease.expiration_date': 'Fecha de Vencimiento',
    'lease.rent_schedule': 'Calendario de Renta',
    'lease.financial_terms': 'Términos Financieros Adicionales',
    'lease.base_rent': 'Renta Base (Legado)',
    'lease.rent_frequency': 'Frecuencia de Renta',
    'lease.security_deposit': 'Depósito de Seguridad',
    'lease.escalation_clauses': 'Cláusulas de Escalación (Descripción)',
    'lease.additional_terms': 'Términos Adicionales',
    'lease.renewal_options': 'Opciones de Renovación',
    'lease.termination_clauses': 'Cláusulas de Terminación',
    'lease.key_dates': 'Fechas Clave y Notificaciones',
    'lease.document': 'Documento',
    'lease.download_original': 'Descargar Original',
    'lease.identified_risks': 'Riesgos Identificados',
    'lease.no_risks': 'No se identificaron riesgos',
    'lease.status': 'Estado',
    'lease.approve': 'Aprobar Arrendamiento',
    'lease.approved': 'Aprobado',
    'lease.active': 'Activo',
    'lease.confirm': 'Confirmar',
    'lease.edit': 'Editar',
    'lease.save': 'Guardar',
    'lease.back': 'Volver',
    'lease.finalize': 'Finalizar',
    'lease.review_required': 'Revisión Requerida',
    'lease.review_edit_info': 'Revise y edite la información extraída a continuación, luego guarde sus cambios antes de finalizar.',
    'lease.finalized': 'Finalizado',
    'lease.finalized_info': 'Este arrendamiento ha sido revisado y finalizado.',
    'lease.approved_info': 'Este arrendamiento ha sido aprobado y ahora está activo.',
    'lease.processing': 'Procesando',
    'lease.uploaded': 'Subido',
    'lease.ready': 'Listo',
    'lease.failed': 'Fallido',
    'lease.ai_risks_desc': 'Problemas potenciales identificados por IA en este arrendamiento',
    'lease.not_found': 'Arrendamiento no encontrado',
    'lease.back_to_leases': 'Volver a Arrendamientos',
    'lease.draft': 'Borrador',
    'lease.needs_review': 'Necesita Revisión',
    'lease.archived': 'Archivado',
    'lease.amendment': 'Enmienda',
    'lease.address_pending': 'Dirección pendiente',
    
    // Rent Schedule
    'rent_schedule.title': 'Calendario de Renta',
    'rent_schedule.description': 'Historial completo de renta extraído del documento de arrendamiento',
    'rent_schedule.current_monthly': 'Renta Mensual Actual',
    'rent_schedule.escalation_type': 'Tipo de Escalación',
    'rent_schedule.next_increase': 'Próximo Aumento',
    'rent_schedule.not_specified': 'No especificado',
    'rent_schedule.period': 'Período',
    'rent_schedule.monthly': 'Mensual',
    'rent_schedule.annual': 'Anual',
    'rent_schedule.notes': 'Notas',
    'rent_schedule.current': 'Actual',
    'rent_schedule.ongoing': 'En curso',
    'rent_schedule.no_schedule': 'No se extrajo calendario de renta',
    'rent_schedule.check_base_rent': 'La información de renta puede estar en los campos de renta base',
    
    // Leases Page
    'leases.title': 'Arrendamientos',
    'leases.portfolio': 'Su portafolio de arrendamientos',
    'leases.search': 'Buscar arrendamientos...',
    'leases.filter_expiration': 'Filtrar por vencimiento',
    'leases.all_leases': 'Todos los arrendamientos',
    'leases.expiring_30': 'Vencen en 30 días',
    'leases.expiring_90': 'Vencen en 90 días',
    'leases.expiring_year': 'Vencen este año',
    'leases.property': 'Propiedad',
    'leases.tenant': 'Arrendatario',
    'leases.landlord': 'Arrendador',
    'leases.dates': 'Fechas',
    'leases.rent': 'Renta',
    'leases.sqft': 'Pies Cuad.',
    'leases.start': 'Inicio',
    'leases.end': 'Fin',
    'leases.actions': 'Acciones',
    'leases.no_leases': 'Sin arrendamientos',
    'leases.upload_first': 'Suba su primer arrendamiento para comenzar',
    'leases.no_match': 'Ningún arrendamiento coincide con sus filtros',
    'leases.view_details': 'Ver detalles',
    'leases.delete': 'Eliminar',
    'leases.expired': 'Vencido',
    'leases.active_leases': 'arrendamientos activos',
    
    // Import History
    'import.history': 'Historial de Importaciones',
    'import.documents_imported': 'documentos importados',
    'import.upload_lease': 'Subir Arrendamiento',
    'import.no_imports': 'Sin importaciones aún',
    'import.upload_first': 'Suba su primer documento de arrendamiento para comenzar',
    'import.search_filename': 'Buscar por nombre de archivo...',
    'import.filename': 'Nombre del Archivo',
    'import.uploaded': 'Subido',
    'import.processed': 'Procesado',
    'import.actions': 'Acciones',
    'import.retry': 'Reintentar',
    'import.view': 'Ver arrendamiento',
    'import.delete': 'Eliminar',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.subtitle': 'Manténgase al día con fechas importantes',
    'notifications.no_notifications': 'Sin notificaciones',
    'notifications.all_caught_up': '¡Está al día!',
    'notifications.view_all': 'Ver todas las notificaciones',
    'notifications.tab_all': 'Todas Confirmadas',
    'notifications.tab_upcoming': 'Alertas Próximas',
    'notifications.tab_sent': 'Ya Enviadas',
    'notifications.view_leases': 'Ver Arrendamientos',
    'notifications.view_lease': 'Ver Arrendamiento',
    'notifications.disable': 'Desactivar Notificaciones',
    'notifications.type.renewal_window': 'Ventana de Renovación',
    'notifications.type.escalation': 'Escalación de Renta',
    'notifications.type.expiration': 'Vencimiento del Arrendamiento',
    'notifications.type.commencement': 'Inicio del Arrendamiento',
    'notifications.type.custom': 'Personalizada',
    'notifications.sent': 'Enviado',
    'notifications.scheduled': 'Programado',
    'notifications.past': 'Pasado',
    'notifications.email_off': 'Email Desactivado',
    'notifications.alerts': 'Alertas',
    'notifications.days_before': 'días antes',
    'notifications.unknown_property': 'Propiedad Desconocida',
    'notifications.hours_ago': 'hace {{count}} horas',
    'notifications.day_ago': 'hace {{count}} día',
    'notifications.custom': 'Personalizada',
    
    // Notification Detail
    'notifications.detail_title': 'Detalles de Notificación',
    'notifications.not_found': 'Notificación no encontrada',
    'notifications.back_to_list': 'Volver a Notificaciones',
    'notifications.error_loading': 'Error al cargar notificación',
    'notifications.error_updating': 'Error al actualizar notificación',
    'notifications.email_disabled': 'Notificaciones por email desactivadas',
    'notifications.email_enabled': 'Notificaciones por email activadas',
    'notifications.confirmed': 'Confirmada',
    'notifications.days_ago': 'hace {{count}} días',
    'notifications.days_remaining': '{{count}} días restantes',
    'notifications.event_passed': 'El evento ya pasó',
    'notifications.time_remaining': 'Tiempo restante',
    'notifications.associated_lease': 'Arrendamiento Asociado',
    'notifications.email_settings': 'Notificaciones por Email',
    'notifications.email_on': 'Alertas por email activadas',
    'notifications.alert_schedule': 'Calendario de alertas',
    'notifications.enable': 'Activar',
    'notifications.last_sent': 'Última notificación enviada',
    
    // Notification Configurator
    'notifications.config.title': 'Fechas Clave y Notificaciones',
    'notifications.config.description': 'Confirme fechas y active notificaciones para eventos importantes',
    'notifications.config.confirmed_count': 'confirmadas',
    'notifications.config.active_alerts': 'alertas activas',
    'notifications.config.no_dates': 'No se encontraron fechas clave. Agregue fechas arriba para configurar notificaciones.',
    'notifications.config.unconfirmed': 'Sin confirmar',
    'notifications.config.notify_me': 'Notificarme:',
    'notifications.config.email_enabled': 'Email activado',
    'notifications.config.off': 'Desactivado',
    'notifications.config.unconfirm': 'Desconfirmar',
    'notifications.config.add_custom': 'Agregar Fecha Personalizada',
    'notifications.config.date': 'Fecha',
    'notifications.config.description_label': 'Descripción',
    'notifications.config.description_placeholder': 'ej., Fecha límite de renovación de seguro',
    'notifications.config.add_date': 'Agregar Fecha',
    'notifications.config.save': 'Guardar Preferencias de Notificación',
    'notifications.config.days_before': 'días antes',
    'notifications.config.lease_commencement': 'Inicio del Arrendamiento',
    'notifications.config.lease_expiration': 'Vencimiento del Arrendamiento',
    'notifications.config.renewal_window': 'Ventana de Renovación',
    'notifications.config.rent_escalation': 'Escalación de Renta',
    'notifications.config.custom_date': 'Fecha Personalizada',
    'notifications.config.commencement_desc': 'Fecha de inicio del arrendamiento',
    'notifications.config.expiration_desc': 'Fecha de vencimiento del arrendamiento',
    'notifications.config.renewal_desc': 'Ventana de decisión de renovación abre',
    'notifications.config.escalation_desc': 'Escalación de renta a',
    'notifications.config.per_month': '/mes',
    
    // Account Settings
    'account.title': 'Configuración de Cuenta',
    'account.subtitle': 'Administre su cuenta personal',
    'account.profile': 'Perfil',
    'account.security': 'Seguridad',
    'account.notifications': 'Notificaciones',
    'account.data_privacy': 'Datos y Privacidad',
    'account.subscription': 'Suscripción',
    'account.personal_info': 'Información Personal',
    'account.update_details': 'Actualice sus datos personales',
    'account.first_name': 'Nombre',
    'account.last_name': 'Apellido',
    'account.email': 'Correo Electrónico',
    'account.phone': 'Teléfono (para notificaciones SMS)',
    'account.company': 'Nombre de la Empresa',
    'account.timezone': 'Zona Horaria',
    'account.save_changes': 'Guardar Cambios',
    'account.saving': 'Guardando...',
    'account.change_password': 'Cambiar Contraseña',
    'account.update_password': 'Actualice la contraseña de su cuenta',
    'account.current_password': 'Contraseña Actual',
    'account.new_password': 'Nueva Contraseña',
    'account.confirm_password': 'Confirmar Nueva Contraseña',
    'account.update_password_btn': 'Actualizar Contraseña',
    'account.updating': 'Actualizando...',
    'account.security_activity': 'Actividad de Seguridad Reciente',
    'account.review_logins': 'Revise inicios de sesión y eventos de seguridad recientes',
    'account.current_session': 'Sesión actual',
    'account.password_changed': 'Contraseña cambiada',
    'account.logout_other': 'Cerrar otras sesiones',
    'account.notification_prefs': 'Preferencias de Notificación',
    'account.choose_alerts': 'Elija cómo desea recibir alertas',
    'account.email_notifications': 'Notificaciones por Email',
    'account.email_notifications_desc': 'Reciba alertas de arrendamiento por correo',
    'account.sms_notifications': 'Notificaciones SMS',
    'account.sms_notifications_desc': 'Reciba alertas críticas por SMS',
    'account.quiet_hours': 'Horas de Silencio',
    'account.quiet_hours_desc': 'No enviar notificaciones entre 10 PM - 7 AM',
    'account.export_data': 'Exportar Sus Datos',
    'account.export_data_desc': 'Descargue una copia de todos sus datos en este espacio de trabajo',
    'account.export_archive': 'Esto creará un archivo descargable con todos sus arrendamientos, datos extraídos e información de cuenta.',
    'account.export_btn': 'Exportar Datos',
    'account.exporting': 'Exportando...',
    'account.delete_account': 'Eliminar Cuenta',
    'account.delete_account_desc': 'Elimine permanentemente su cuenta y todos los datos asociados',
    'account.delete_warning': 'Esta acción no se puede deshacer. Todos sus datos, incluyendo arrendamientos, información extraída y configuración del espacio de trabajo serán eliminados permanentemente.',
    'account.delete_confirm': '¿Está absolutamente seguro?',
    'account.delete_confirm_desc': 'Esta acción no se puede deshacer. Esto eliminará permanentemente su cuenta y todos sus datos de nuestros servidores.',
    'account.current_plan': 'Plan Actual',
    'account.renews_on': 'Su suscripción se renueva el',
    'account.document_usage': 'Uso de Documentos',
    'account.manage_payment': 'Administrar Método de Pago',
    'account.billing_contact': 'Contacto de Facturación',
    'account.invoices_sent': 'Las facturas se envían a este correo',
    'account.update_billing': 'Actualizar Contacto de Facturación',
    'account.available_plans': 'Planes Disponibles',
    'account.invoice_history': 'Historial de Facturas',
    'account.download_invoices': 'Descargue facturas anteriores para sus registros',
    'account.cancel_subscription': 'Cancelar Suscripción',
    'account.cancel_subscription_desc': 'Cancele su suscripción al final del período de facturación actual',
    'account.cancel_warning': 'Su suscripción permanecerá activa hasta el final de su período de facturación actual. Puede reactivarla en cualquier momento antes.',
    'account.cancel_confirm': '¿Cancelar su suscripción?',
    'account.cancel_confirm_desc': 'Su suscripción permanecerá activa hasta el final de su período de facturación actual. Después, perderá acceso a las funciones premium.',
    'account.keep_subscription': 'Mantener Suscripción',
    'account.free': 'Gratis',
    'account.current': 'Actual',
    'account.downgrade': 'Degradar',
    'account.free_tier': 'Nivel Gratis',
    'account.leases': 'arrendamientos',
    'account.lease': 'arrendamiento',
    'account.paid': 'Pagado',
    
    // Workspace Settings
    'workspace.title': 'Configuración del Espacio de Trabajo',
    'workspace.subtitle': 'Administre la configuración de su espacio de trabajo',
    'workspace.general': 'General',
    'workspace.members': 'Miembros',
    'workspace.notifications': 'Notificaciones',
    'workspace.security': 'Seguridad',
    'workspace.details': 'Detalles del Espacio de Trabajo',
    'workspace.basic_info': 'Información básica sobre su espacio de trabajo',
    'workspace.name': 'Nombre del Espacio de Trabajo',
    'workspace.default_timezone': 'Zona Horaria Predeterminada',
    'workspace.timezone_desc': 'Se usa para programar notificaciones y mostrar fechas',
    'workspace.save_changes': 'Guardar Cambios',
    'workspace.saving': 'Guardando...',
    'workspace.team_members': 'Miembros del Equipo',
    'workspace.manage_access': 'Administre quién tiene acceso a este espacio de trabajo',
    'workspace.invite_member': 'Invitar Miembro',
    'workspace.no_members': 'Sin miembros del equipo aún',
    'workspace.only_one': 'Usted es el único con acceso a este espacio de trabajo',
    'workspace.owner': 'Propietario',
    'workspace.admin': 'Administrador',
    'workspace.editor': 'Editor',
    'workspace.viewer': 'Visor',
    'workspace.notification_settings': 'Configuración de Notificaciones Predeterminada',
    'workspace.notification_timing': 'Configure el tiempo predeterminado para las notificaciones de arrendamiento',
    'workspace.reminder_days': 'Recordatorio Predeterminado (días antes)',
    'workspace.reminder_desc': 'Cuántos días antes de un evento enviar la primera notificación',
    'workspace.audit_log': 'Registro de Auditoría',
    'workspace.view_activity': 'Vea la actividad reciente en su espacio de trabajo',
    'workspace.logs_appear': 'Los registros de auditoría aparecerán aquí',
    
    // Integrations
    'integrations.title': 'Integraciones',
    'integrations.subtitle': 'Conecte LeaseIO con sus otras herramientas',
    'integrations.quickbooks': 'QuickBooks Online',
    'integrations.quickbooks_desc': 'Sincronice pagos de arrendamiento con su sistema contable. Automatice la creación de facturas y seguimiento de pagos.',
    'integrations.email': 'Notificaciones por Email',
    'integrations.email_desc': 'Envíe alertas automáticas por email para renovaciones, escalaciones y vencimientos.',
    'integrations.sms': 'Notificaciones SMS',
    'integrations.sms_desc': 'Reciba alertas críticas de arrendamiento por SMS para eventos urgentes.',
    'integrations.connected': 'Conectado',
    'integrations.configure': 'Configurar',
    'integrations.disconnect': 'Desconectar',
    'integrations.connect': 'Conectar',
    'integrations.upgrade_business': 'Actualizar a Empresarial',
    'integrations.guide': 'Guía de Integración',
    'integrations.guide_desc': 'Aprenda a aprovechar al máximo sus integraciones',
    'integrations.step1': '1. Conecte Su Cuenta',
    'integrations.step1_desc': 'Use OAuth para conectar de forma segura sus cuentas externas sin compartir contraseñas.',
    'integrations.step2': '2. Configure Ajustes',
    'integrations.step2_desc': 'Elija cómo deben fluir los datos entre LeaseIO y sus servicios conectados.',
    'integrations.step3': '3. Monitoree Actividad',
    'integrations.step3_desc': 'Revise los registros de sincronización y resuelva problemas desde el panel de integración.',
    
    // Reports
    'reports.title': 'Informes',
    'reports.subtitle': 'Análisis e información del portafolio',
    'reports.export_all': 'Exportar Todo',
    'reports.rent_roll': 'Exportar Rol de Rentas',
    'reports.rent_roll_desc': 'Descargue un rol de rentas completo de su portafolio como archivo CSV',
    'reports.rent_roll_details': 'Incluye detalles de propiedades, información de arrendatarios, montos de renta, fechas de arrendamiento y un resumen del portafolio. Compatible con Excel y Google Sheets.',
    'reports.download_rent_roll': 'Descargar Rol de Rentas',
    'reports.generating': 'Generando...',
    'reports.portfolio_overview': 'Resumen del Portafolio',
    'reports.portfolio_overview_desc': 'Resumen de alto nivel de todos los arrendamientos activos, renta comprometida total y métricas clave.',
    'reports.renewal_pipeline': 'Pipeline de Renovaciones',
    'reports.renewal_pipeline_desc': 'Rastree renovaciones próximas con impacto proyectado y recomendaciones de acción.',
    'reports.escalation_calendar': 'Calendario de Escalaciones',
    'reports.escalation_calendar_desc': 'Vea todas las escalaciones de renta programadas con aumentos proyectados.',
    'reports.rent_projections': 'Proyecciones de Renta',
    'reports.rent_projections_desc': 'Proyecte obligaciones de renta futuras basadas en términos actuales y escalaciones.',
    'reports.view_report': 'Ver Informe',
    'reports.monthly_overview': 'Resumen Mensual de Rentas',
    'reports.monthly_overview_desc': 'Renta comprometida total en todos los arrendamientos activos',
    'reports.charts_appear': 'Los gráficos aparecerán cuando tenga arrendamientos finalizados',
    'reports.unlock_advanced': 'Desbloquear Informes Avanzados',
    'reports.unlock_desc': 'Actualice al plan Empresarial para acceder a análisis de portafolio, pipelines de renovación, calendarios de escalación y proyecciones de renta.',
    
    // Empty States
    'empty.no_leases': 'Sin arrendamientos aún',
    'empty.upload_first': 'Suba su primer documento de arrendamiento para comenzar. Nuestra IA extraerá automáticamente términos clave, fechas e información financiera para usted.',
    'empty.upload_first_lease': 'Suba Su Primer Arrendamiento',
    'empty.supports_pdf': 'Soporta archivos PDF hasta 50MB',
    
    // Common
    'common.confirm': 'Confirmar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.back': 'Volver',
    'common.upload': 'Subir',
    'common.processing': 'Procesando',
    'common.loading': 'Cargando...',
    'common.page': 'Página',
    'common.search': 'Buscar',
    'common.view': 'Ver',
    'common.download': 'Descargar',
    'common.upgrade': 'Actualizar',
    'common.business_plan': 'Plan Empresarial',
    'common.search_placeholder': 'Buscar arrendamientos, partes, propiedades...',
    
    // Plan labels
    'plan.free': 'Gratis',
    'plan.starter': 'Inicial',
    'plan.pro': 'Pro',
    'plan.business': 'Empresarial',
    'plan.plan': 'Plan',
    'plan.upgrade': 'Actualizar',
    
    // Plan Features
    'plan.feature.lease_documents': 'documentos de arrendamiento',
    'plan.feature.ai_extraction': 'Extracción de arrendamientos con IA',
    'plan.feature.basic_tracking': 'Seguimiento básico de renta',
    'plan.feature.email_notifications': 'Notificaciones por email',
    'plan.feature.rent_schedule': 'Seguimiento de calendario de renta',
    'plan.feature.rent_roll': 'Exportación de rol de rentas',
    'plan.feature.document_storage': 'Almacenamiento de documentos',
    'plan.feature.sms': 'Notificaciones SMS',
    'plan.feature.risk_analysis': 'Análisis de riesgos',
    'plan.feature.advanced_reports': 'Informes avanzados',
    'plan.feature.priority_support': 'Soporte prioritario',
    'plan.feature.team_access': 'Acceso de equipo (5 puestos)',
    'plan.feature.role_permissions': 'Permisos basados en roles',
    'plan.feature.quickbooks': 'Integración con QuickBooks',
    'plan.feature.custom_branding': 'Marca personalizada',
    'plan.feature.everything_starter': 'Todo en Inicial',
    'plan.feature.everything_pro': 'Todo en Pro',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('app-language');
    return (stored as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    
    // Replace template parameters like {{count}}
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        text = text.replace(new RegExp(`\\{\\{${paramKey}\\}\\}`, 'g'), String(paramValue));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
